#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: e9fa5a5c-6689-4397-b9b7-e054e46c52c0
#        group: dev
    gateway:
      routes:
        # 精确的路由要放在/api的admin_route上面
        #产品模块路由
        - id: product_route
          uri: lb://watermall-product        #路由的目标地址
          predicates:                    # 路由断言。也就是判断请求是否符合路由规则的条件。
            - Path=/api/product/**        # 路径断言。这个是按照路径匹配，只要以/api/product/开头就符合要求
          filters:        #局部过滤器
            - RewritePath=/api/(?<segment>.*),/$\{segment}    #重写路径，/api/xx过滤成/xx
        #用户模块路由
        - id: member_route
          uri: lb://watermall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        #仓储模块路由
        - id: ware_route
          uri: lb://watermall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        #优惠券模块路由
        - id: ware_route
          uri: lb://watermall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 路由id，自定义，只要唯一即可
        - id: admin_route
          # uri路由的目标地址。lb就是负载均衡，后面跟服务名称。
          uri: lb://renren-fast
          #断言工厂的Path，请求路径必须符合指定规则
          predicates:
            - Path=/api/**    # 把所有api开头的请求都转发给renren-fast
          #局部过滤器。回顾默认过滤器default-filters是与routes同级
          filters:
            #路径重写。逗号左边是原路径，右边是重写后的路径
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
            # 默认规则， 请求过来：http://localhost:88/api/captcha.jpg   转发-->  http://renren-fast:8080/renren-fast/captcha.jpg
  application:
    name: watermall-gateway
#应用名称在nacos也配置了，防止迁移之后无nacos，所以这里也做配置
server:
  port: 88

