spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
    sms:
      host: https://gyytz.market.alicloudapi.com
      path: /sms/smsSend
      method: POST
      appcode: b5ee94a931614741b7c69a77f879e348
      smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
      templateId: 908e94ccf08b4476ba6c876d13f084ad
  application:
    name: watermall-third-party
server:
  port: 43000


logging:
  level:
    com.atcode.watermall.thirdparty: debug
