spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: watermall-third-party
server:
  port: 43000


logging:
  level:
    com.atcode.watermall.thirdparty: debug
