spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: ed02e004-02e9-43df-95e0-9f4a3c8c069f
#        group: dev
  application:
    name: watermall-product

# 关闭thymeleaf缓存，以便于修改代码后刷新页面能看出修改
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 12000


logging:
  level:
#    com.atcode.watermall.product: error
    com.atcode.watermall.product: debug
