spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #        namespace: ed02e004-02e9-43df-95e0-9f4a3c8c069f
  #        group: dev
  application:
    name: watermall-search
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html





logging:
  level:
    com.atcode.watermall.search: debug
